---
title: "p8105_hw2_hy2958"
output: github_document
---

```{r setup}
library(tidyverse)
```

problem 1.1

```{r}
pols = 
  read_csv("./data/fivethirtyeight_datasets/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, into = c("year", "month", "day"), sep='-', convert = TRUE)  %>% 
  mutate (month = case_when(
    month == 1 ~ "January",
    month == 2 ~ "February",
    month == 3 ~ "March",
    month == 4 ~ "April",
    month == 5 ~ "May",
    month == 6 ~ "June",
    month == 7 ~ "July",
    month == 8 ~ "August",
    month == 9 ~ "September",
    month == 10 ~ "October",
    month == 11 ~ "November",
    month == 12 ~ "December")) %>% 
  mutate (president = case_when (
    prez_gop == 1 ~ "republican",
    prez_dem == 1 ~ "democratic")) %>% 
  select (-prez_gop, -prez_dem, -day)
  
```
problem 1.2

```{r}
snp = 
  read_csv("./data/fivethirtyeight_datasets/snp.csv") %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("month", "day", "year"), sep='/', convert = TRUE)  %>% 
  mutate (year=year+2000) %>%
  mutate (year=case_when (year>2025 ~ year-100, year<=2025 ~ year)) %>%
  select (-day) %>% 
  mutate (month = case_when(
    month == 1 ~ "January",
    month == 2 ~ "February",
    month == 3 ~ "March",
    month == 4 ~ "April",
    month == 5 ~ "May",
    month == 6 ~ "June",
    month == 7 ~ "July",
    month == 8 ~ "August",
    month == 9 ~ "September",
    month == 10 ~ "October",
    month == 11 ~ "November",
    month == 12 ~ "December")) %>% 
  relocate(year)

```

problem 1.3

```{r}
unemployment = 
  read_csv("./data/fivethirtyeight_datasets/unemployment.csv") %>% 
  janitor::clean_names() %>%
  pivot_longer(
    jan:dec,
    names_to = "month", 
    values_to = "unemployment_pec") %>% 
    mutate (month = case_when(
    month == 'jan' ~ "January",
    month == 'feb' ~ "February",
    month == 'mar' ~ "March",
    month == 'apr' ~ "April",
    month == 'may' ~ "May",
    month == 'jun' ~ "June",
    month == 'jul' ~ "July",
    month == 'aug' ~ "August",
    month == 'sep' ~ "September",
    month == 'oct' ~ "October",
    month == 'nov' ~ "November",
    month == 'dec' ~ "December"))
```
merge

```{r}
data=left_join (pols, snp, by = c ("year", "month"))
data_final=left_join (data, unemployment,  by = c ("year", "month"))
```

